# Generated by Django 4.0.4 on 2022-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('employee_id', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
