# Generated by Django 4.1.3 on 2022-11-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
