# Generated by Django 4.1.3 on 2022-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee",
            "0002_remove_employee_id_remove_employee_profile_picture_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
